// This script runs after 'npx update-browserslist-db@latest'
// Use it to clear caches, rebuild, or log results.

import { getUserAgentRegex } from 'browserslist-useragent-regexp';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

console.log("Browserslist update complete.");
console.log("Running post-update tasks...");

async function generateUserAgentRegex() {
    try {
        console.log("Generating user-agent regex...");
        const regex = await getUserAgentRegex({
            allowHigherVersions: true,
        });

        const targetFile = path.join(__dirname, '../src/userAgentRegex.ts');
        const content = `// This file is auto-generated by scripts/after-update.js
// Do not edit this file manually.

export const userAgentRegex = /${regex.source}/;
`;

        fs.writeFileSync(targetFile, content);
        console.log(`User-agent regex saved to ${targetFile}`);
    } catch (error) {
        console.error("Failed to generate user-agent regex:", error);
        process.exit(1);
    }
}

generateUserAgentRegex();

console.log("Post-update tasks finished successfully.");
